-- MySQL Script generated by MySQL Workbench
-- Thu Mar 22 11:42:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homRight
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homRight
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homRight` DEFAULT CHARACTER SET utf8 ;
USE `homRight` ;

-- -----------------------------------------------------
-- Table `homRight`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `avatar` VARCHAR(255) NULL,
  `pseudo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(150) NOT NULL,
  `prenom` VARCHAR(150) NOT NULL,
  `date_creation` DATETIME NULL,
  `budget` FLOAT NULL,
  `longitude` FLOAT NULL,
  `latitude` FLOAT NULL,
  `point` INT NULL,
  `point_niv` INT NULL,
  `email_n` TINYINT(1) NULL,
  `push` TINYINT(1) NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `homRight`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`coupon` (
  `coupon_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `code` VARCHAR(100) NULL,
  `description` LONGTEXT NULL,
  `nb_points` INT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`coupon_id`, `user_user_id`),
  INDEX `fk_coupon_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_coupon_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `homRight`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`badge` (
  `niveau` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`niveau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`evenement` (
  `evenement_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NULL,
  `date_debut` DATETIME NULL,
  `date_fin` DATETIME NULL,
  `lieu` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `point_event` INT NULL,
  `badge_event` INT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`evenement_id`, `user_user_id`),
  INDEX `fk_evenement_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_evenement_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `homRight`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`shop` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `voie` VARCHAR(255) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(255) NULL,
  `site` VARCHAR(255) NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`shop_id`, `user_user_id`),
  INDEX `fk_shop_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_shop_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `homRight`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`item` (
  `item_id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `categorie` VARCHAR(150) NULL,
  `prix` FLOAT NULL,
  `description` LONGTEXT NULL,
  `commentaire` LONGTEXT NULL,
  `note` FLOAT NULL,
  `shop_shop_id` INT NOT NULL,
  `shop_user_user_id` INT NOT NULL,
  PRIMARY KEY (`item_id`, `shop_shop_id`, `shop_user_user_id`),
  INDEX `fk_item_shop1_idx` (`shop_shop_id` ASC, `shop_user_user_id` ASC),
  CONSTRAINT `fk_item_shop1`
    FOREIGN KEY (`shop_shop_id` , `shop_user_user_id`)
    REFERENCES `homRight`.`shop` (`shop_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`maison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`maison` (
  `maison_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `compt_linky` INT NULL,
  `fournisseur` VARCHAR(150) NULL,
  `contrat` VARCHAR(255) NULL,
  `nb_habitants` INT NULL,
  `superficie` INT NULL,
  `volets_fermes` TINYINT(1) NULL,
  `chauffage_reduit` TINYINT(1) NULL,
  `voie` VARCHAR(255) NULL,
  `immeuble` VARCHAR(255) NULL,
  `bp` VARCHAR(255) NULL,
  `cp` INT NULL,
  `ville` VARCHAR(255) NULL,
  `estPublique` TINYINT(1) NULL,
  PRIMARY KEY (`maison_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`conso_maison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`conso_maison` (
  `conso_maison_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `valeur_conso` FLOAT NULL,
  `eq_euros` FLOAT NULL,
  `eq_carbone` FLOAT NULL,
  `maison_maison_id` INT NOT NULL,
  `maison_user_user_id` INT NOT NULL,
  PRIMARY KEY (`conso_maison_id`, `maison_maison_id`, `maison_user_user_id`),
  INDEX `fk_conso_maison_maison1_idx` (`maison_maison_id` ASC, `maison_user_user_id` ASC),
  CONSTRAINT `fk_conso_maison_maison1`
    FOREIGN KEY (`maison_maison_id`)
    REFERENCES `homRight`.`maison` (`maison_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`piece` (
  `piece_id` INT NOT NULL AUTO_INCREMENT,
  `temperature` INT NULL,
  `nom` VARCHAR(255) NULL,
  `maison_maison_id` INT NOT NULL,
  `longueur` INT NULL,
  `largeur` INT NULL,
  PRIMARY KEY (`piece_id`, `maison_maison_id`),
  INDEX `fk_piece_maison1_idx` (`maison_maison_id` ASC),
  CONSTRAINT `fk_piece_maison1`
    FOREIGN KEY (`maison_maison_id`)
    REFERENCES `homRight`.`maison` (`maison_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`type_piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`type_piece` (
  `type_piece_id` INT NOT NULL AUTO_INCREMENT,
  `type_piece_nom` VARCHAR(100) NULL,
  PRIMARY KEY (`type_piece_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`conso_piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`conso_piece` (
  `conso_piece_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `valeur_conso` FLOAT NULL,
  `eq_euros` FLOAT NULL,
  `eq_carbone` FLOAT NULL,
  `piece_piece_id` INT NOT NULL,
  PRIMARY KEY (`conso_piece_id`, `piece_piece_id`),
  INDEX `fk_conso_piece_piece1_idx` (`piece_piece_id` ASC),
  CONSTRAINT `fk_conso_piece_piece1`
    FOREIGN KEY (`piece_piece_id`)
    REFERENCES `homRight`.`piece` (`piece_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`equipement` (
  `appareil_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `est_connecte` TINYINT(1) NULL,
  `est_actif` TINYINT(1) NULL,
  `piece_piece_id` INT NOT NULL,
  `positionX` INT NULL,
  `positionY` INT NULL,
  PRIMARY KEY (`appareil_id`, `piece_piece_id`),
  INDEX `fk_appareil_piece1_idx` (`piece_piece_id` ASC),
  CONSTRAINT `fk_appareil_piece1`
    FOREIGN KEY (`piece_piece_id`)
    REFERENCES `homRight`.`piece` (`piece_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`conso_appareil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`conso_appareil` (
  `conso_appareil_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `valeur_conso` FLOAT NULL,
  `eq_euros` FLOAT NULL,
  `eq_carbone` FLOAT NULL,
  `appareil_appareil_id` INT NOT NULL,
  PRIMARY KEY (`conso_appareil_id`, `appareil_appareil_id`),
  INDEX `fk_conso_appareil_appareil1_idx` (`appareil_appareil_id` ASC),
  CONSTRAINT `fk_conso_appareil_appareil1`
    FOREIGN KEY (`appareil_appareil_id`)
    REFERENCES `homRight`.`equipement` (`appareil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`user_has_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`user_has_badge` (
  `user_user_id` INT NOT NULL,
  `badge_niveau` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `badge_niveau`),
  INDEX `fk_user_has_badge_badge1_idx` (`badge_niveau` ASC),
  INDEX `fk_user_has_badge_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_badge_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `homRight`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_badge_badge1`
    FOREIGN KEY (`badge_niveau`)
    REFERENCES `homRight`.`badge` (`niveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `homRight`.`piece_has_type_piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`piece_has_type_piece` (
  `piece_piece_id` INT NOT NULL,
  `type_piece_type_piece_id` INT NOT NULL,
  PRIMARY KEY (`piece_piece_id`, `type_piece_type_piece_id`),
  INDEX `fk_piece_has_type_piece_type_piece1_idx` (`type_piece_type_piece_id` ASC),
  INDEX `fk_piece_has_type_piece_piece1_idx` (`piece_piece_id` ASC),
  CONSTRAINT `fk_piece_has_type_piece_piece1`
    FOREIGN KEY (`piece_piece_id`)
    REFERENCES `homRight`.`piece` (`piece_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piece_has_type_piece_type_piece1`
    FOREIGN KEY (`type_piece_type_piece_id`)
    REFERENCES `homRight`.`type_piece` (`type_piece_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`scene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`scene` (
  `scene_id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `icone` VARCHAR(255) NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`scene_id`, `user_user_id`),
  INDEX `fk_scene_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_scene_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `homRight`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`scene_has_piece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`scene_has_piece` (
  `scene_scene_id` INT NOT NULL,
  `scene_user_user_id` INT NOT NULL,
  `piece_piece_id` INT NOT NULL,
  `piece_maison_maison_id` INT NOT NULL,
  PRIMARY KEY (`scene_scene_id`, `scene_user_user_id`, `piece_piece_id`, `piece_maison_maison_id`),
  INDEX `fk_scene_has_piece_piece1_idx` (`piece_piece_id` ASC, `piece_maison_maison_id` ASC),
  INDEX `fk_scene_has_piece_scene1_idx` (`scene_scene_id` ASC, `scene_user_user_id` ASC),
  CONSTRAINT `fk_scene_has_piece_scene1`
    FOREIGN KEY (`scene_scene_id` , `scene_user_user_id`)
    REFERENCES `homRight`.`scene` (`scene_id` , `user_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scene_has_piece_piece1`
    FOREIGN KEY (`piece_piece_id` , `piece_maison_maison_id`)
    REFERENCES `homRight`.`piece` (`piece_id` , `maison_maison_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homRight`.`user_has_maison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homRight`.`user_has_maison` (
  `user_user_id` INT NOT NULL,
  `maison_maison_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `maison_maison_id`),
  INDEX `fk_user_has_maison_maison1_idx` (`maison_maison_id` ASC),
  INDEX `fk_user_has_maison_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_maison_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `homRight`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_maison_maison1`
    FOREIGN KEY (`maison_maison_id`)
    REFERENCES `homRight`.`maison` (`maison_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
